


spring:
  datasource:
    url:               ${DB_URL:jdbc:h2:/tmp/db/h2/activiti.h2;AUTO_SERVER=TRUE;MODE=MYSQL;}
    username:          ${DB_USERNAME:sa}
    password:          ${DB_PASSWORD:sa}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  security:
    user:
      name:     forsrc
      password: forsrc

